
- name: install virtualenv
  hosts: hypervisor
  vars: 
    ansible_user: nitram
  roles:

    - name: ../../roles/python-virtualenv
      vars:
        virtualenv_python: /usr/bin/python2.7
        virtualenv_command: /usr/bin/virtualenv # os dist python
        virtualenv_path: /opt/dev/venv2
        virtualenv_user: root
        
        virtualenv_requirements_path: "/opt/dev"
        virtualenv_requirements:
          - "{{ virtualenv_requirements_path }}/requirements.txt"
  
  handlers:
    - name: custom virtualenv handler
      debug:
        msg: "virtualenv in {{ virtualenv_path }} was updated."
      listen: virtualenv updated