apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  labels:
    storage.k8s.io/name: glusterfs
    storage.k8s.io/part-of: kubernetes-complete-reference
subsets:
  - addresses:
      - ip: 192.168.58.101
        hostname: k8s-1
      - ip: 192.168.58.102
        hostname: k8s-2
      - ip: 192.168.58.103
        hostname: k8s-3
    ports:
      - port: 1