apiVersion: v1
kind: PersistentVolume
metadata:
  name: gv0
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  glusterfs:
    endpoints: glusterfs-cluster
    path: /gv0
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
