---

galaxy_info:
  author: Martin Horejsek
  description: Configure and update a Python virtualenv.
  company: Trask
  license: BSD
  min_ansible_version: 2.x
  platforms:
    - name: EL
      versions:
        - '7'
        - '8'
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - 'buster'
        - 'bullseye'
  galaxy_tags:
    - development
    - packaging
    - python
    - virtualenv
allow_duplicates: true

dependencies:
  - role: pkgs
  # - role: install-python3 # include in playbook when needed
