---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webapp-pv
spec:
  storageClassName: kadalu.storage-pool1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M